#!/bin/bash
set -e

version="0.1"

USAGE="Usage: `basename $0` [-k tag] [-a value] [postfile]"
POST_FILE=""
KEY=""
VALUE=""

#updateJekyllPost -t "length" -v $fileSize $POST_FILE

# Parse command line options.
while getopts "hvk:a:" OPT; do
    case "$OPT" in
        h)
            echo $USAGE
            exit 0
            ;;
        v)
            echo "`basename $0` version $version"
            exit 0
            ;;
        k)
            KEY=$OPTARG
            ;;
        a)
            VALUE=$OPTARG
            ;;
       \?)
            # getopts issues an error message
            echo $USAGE >&2
            exit 1
            ;;
    esac
done

shift $(($OPTIND - 1))

POST_FILE="$@"

if [ ! -f $POST_FILE ]; then
    echo "Can't find the file $POST_FILE"
    exit -1;
fi

sed -e "s/^$KEY:.*$/$KEY: $VALUE/" $POST_FILE > temp.md
mv temp.md $POST_FILE


